# This is a basic workflow to help you get started with Actions

name: Build Electron

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0

      - name: npm install
        run: |
          npm install
          
      - name: build win
        if: matrix.os == 'windows-latest'
        run: |
          npm run build:win64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: cleanup artifacts for windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "build/!(*.exe)"     
          
      - name: build mac
        if: matrix.os == 'macos-latest'
        run: |
          npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: cleanup artifacts for macos
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "build/!(*.dmg)"
          
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: build
